export const styles = {
  container: {
    backgroundColor: 'white',
    borderRadius: 'var(--border-radius-xl)',
    padding: '2rem',
    boxShadow: 'var(--shadow-lg)',
    maxWidth: '600px',
    margin: '0 auto',
  },
  energyBadge: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.75rem 1.5rem',
    backgroundColor: 'var(--color-gray-100)',
    borderRadius: 'var(--border-radius-lg)',
    marginBottom: '1.5rem',
    fontWeight: 600,
    color: 'var(--color-gray-700)',
  },
  energyIcon: {
    fontSize: '1.5rem',
  },
  energyText: {
    fontSize: '1rem',
  },
  modeSelector: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '0.5rem',
    marginBottom: '2rem',
  },
  modeButton: {
    padding: '0.75rem 1rem',
    backgroundColor: 'var(--color-gray-100)',
    color: 'var(--color-gray-700)',
    borderRadius: 'var(--border-radius-md)',
    fontWeight: 600,
    fontSize: '0.875rem',
    transition: 'all var(--transition-fast)',
  },
  modeButtonActive: {
    backgroundColor: 'var(--color-primary)',
    color: 'white',
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1.5rem',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
  },
  label: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'var(--color-gray-700)',
  },
  input: {
    padding: '0.75rem 1rem',
    border: '2px solid var(--color-gray-200)',
    borderRadius: 'var(--border-radius-md)',
    fontSize: '1rem',
    transition: 'border-color var(--transition-fast)',
  },
  fileInput: {
    display: 'none',
  },
  fileUploadBox: {
    border: '2px dashed var(--color-gray-300)',
    borderRadius: 'var(--border-radius-lg)',
    padding: '2rem',
    textAlign: 'center' as const,
    cursor: 'pointer',
    transition: 'all var(--transition-fast)',
  },
  uploadIcon: {
    color: 'var(--color-gray-400)',
    margin: '0 auto 1rem',
  },
  uploadText: {
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-gray-700)',
    marginBottom: '0.25rem',
  },
  uploadSubtext: {
    fontSize: '0.875rem',
    color: 'var(--color-gray-500)',
  },
  recordingSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '1.5rem',
    padding: '2rem',
  },
  recordingDisplay: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  recordingIndicator: {
    width: '1rem',
    height: '1rem',
    borderRadius: '50%',
    backgroundColor: 'var(--color-gray-300)',
    transition: 'all var(--transition-fast)',
  },
  recordingIndicatorActive: {
    backgroundColor: 'var(--color-error)',
    animation: 'pulse 1.5s infinite',
  },
  recordingTime: {
    fontSize: '2rem',
    fontWeight: 700,
    color: 'var(--color-gray-700)',
    fontVariantNumeric: 'tabular-nums',
  },
  waveformContainer: {
    width: '100%',
    marginBottom: '1rem',
  },
  waveformLabel: {
    fontSize: '0.75rem',
    color: 'var(--color-gray-600)',
    marginBottom: '0.5rem',
    textAlign: 'center' as const,
    fontWeight: 500,
  },
  totalWaveformCanvas: {
    width: '100%',
    maxWidth: '600px',
    height: '80px',
    backgroundColor: '#0a0a0a',
    borderRadius: 'var(--border-radius-md)',
    border: '1px solid rgba(59, 130, 246, 0.3)',
    boxShadow: '0 0 15px rgba(59, 130, 246, 0.15)',
  },
  recordingsContainer: {
    width: '100%',
    maxWidth: '600px',
    marginTop: '2rem',
    padding: '1rem',
    backgroundColor: 'rgba(10, 10, 10, 0.3)',
    borderRadius: 'var(--border-radius-md)',
    border: '1px solid rgba(59, 130, 246, 0.2)',
  },
  recordingsTitle: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'var(--color-gray-700)',
    marginBottom: '1rem',
    textAlign: 'center' as const,
  },
  recordingsList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  recordingItem: {
    marginBottom: '1rem',
    padding: '1rem',
    border: '1px solid rgba(59, 130, 246, 0.3)',
    borderRadius: 'var(--border-radius-md)',
    backgroundColor: 'rgba(10, 10, 10, 0.5)',
  },
  recordingControls: {
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'center',
  },
  playButton: {
    padding: '0.5rem 1rem',
    borderRadius: 'var(--border-radius-md)',
    backgroundColor: 'var(--color-primary)',
    color: 'white',
    border: 'none',
    cursor: 'pointer',
  },
  transcribeButton: {
    padding: '0.5rem 1rem',
    borderRadius: 'var(--border-radius-md)',
    backgroundColor: 'var(--color-primary)',
    color: 'white',
    border: 'none',
    cursor: 'pointer',
  },
  downloadLink: {
    padding: '0.5rem 1rem',
    borderRadius: 'var(--border-radius-md)',
    backgroundColor: 'var(--color-gray-200)',
    color: 'var(--color-gray-700)',
    textDecoration: 'none',
    display: 'inline-block',
  },
  waveformCanvas: {
    width: '100%',
    maxWidth: '600px',
    height: '120px',
    backgroundColor: '#0a0a0a',
    borderRadius: 'var(--border-radius-md)',
    border: '1px solid rgba(59, 130, 246, 0.3)',
    boxShadow: '0 0 20px rgba(59, 130, 246, 0.2)',
    marginBottom: '1rem',
  },
  recordingButtons: {
    display: 'flex',
    gap: '1rem',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordButton: {
    padding: '1rem 2rem',
    backgroundColor: 'var(--color-primary)',
    color: 'white',
    borderRadius: 'var(--border-radius-lg)',
    fontWeight: 600,
    fontSize: '1rem',
    transition: 'all var(--transition-fast)',
    border: 'none',
    cursor: 'pointer',
  },
  recordButtonActive: {
    backgroundColor: 'var(--color-error)',
  },
  pauseButton: {
    padding: '1rem 2rem',
    backgroundColor: 'var(--color-gray-600)',
    color: 'white',
    borderRadius: 'var(--border-radius-lg)',
    fontWeight: 600,
    fontSize: '1rem',
    transition: 'all var(--transition-fast)',
    border: 'none',
    cursor: 'pointer',
  },
  error: {
    padding: '0.75rem 1rem',
    backgroundColor: '#fef2f2',
    color: 'var(--color-error)',
    borderRadius: 'var(--border-radius-md)',
    fontSize: '0.875rem',
    border: '1px solid #fee2e2',
  },
  submitButton: {
    padding: '1rem 2rem',
    backgroundColor: 'var(--color-primary)',
    color: 'white',
    borderRadius: 'var(--border-radius-lg)',
    fontWeight: 600,
    fontSize: '1.125rem',
    transition: 'all var(--transition-fast)',
    marginTop: '0.5rem',
  },
  submitButtonDisabled: {
    backgroundColor: 'var(--color-gray-300)',
    cursor: 'not-allowed',
  },
  signInPrompt: {
    textAlign: 'center' as const,
    color: 'var(--color-gray-600)',
    fontSize: '0.875rem',
  },
  link: {
    color: 'var(--color-primary)',
    fontWeight: 600,
  },
  conversionProgress: {
    marginTop: '1rem',
    padding: '1rem',
    backgroundColor: 'var(--color-gray-50)',
    borderRadius: 'var(--border-radius-md)',
    border: '1px solid var(--color-gray-200)',
  },
  progressBarContainer: {
    width: '100%',
    height: '8px',
    backgroundColor: 'var(--color-gray-200)',
    borderRadius: 'var(--border-radius-sm)',
    overflow: 'hidden',
    marginBottom: '0.5rem',
  },
  progressBar: {
    height: '100%',
    backgroundColor: 'var(--color-primary)',
    borderRadius: 'var(--border-radius-sm)',
    transition: 'width 0.3s ease',
    background: 'linear-gradient(90deg, var(--color-primary), #8b5cf6)',
  },
  progressText: {
    fontSize: '0.875rem',
    color: 'var(--color-gray-700)',
    fontWeight: 500,
    textAlign: 'center' as const,
  },
  progressPercent: {
    color: 'var(--color-gray-600)',
    fontWeight: 600,
  },
};

